### ISSUE TITLE
For Datasets add the ability to update "Project of Origin"

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#6] opened 2019-06-15 18:57 UTC
It should be possible to update "Project of origin" field of a dataset. This should only be possible if the dataset has  not yet been linked  to any contract through Data Declarations or Data Shares/Transfers. If the dataset has existing links to contracts, then the update operation should give an error, informing the user highlighting these existing connections.

**Comment by vildead** [comment] 2019-07-29 09:52
@pinarpink  I have several issues:

- when there is a link to contract, error is received but it is very general: "Dataset has indirect references to project **project name**. Please remove those before updating project field.". Is it ok? I am not sure what you mean by **highlighting these existing connections**. It is not clear right away that the indirect reference points to contract and not for example to data declaration. Btw the error message is displayed twice.
- I have created new dataset mapped to new project. When I try to change its the project to an existing one, I get SERVER Error (500). 
Here is a daisy log:
```
ERROR 2019-07-29 11:43:47,254 log 31493 140532733605696 Internal Server Error: /dataset/4/edit
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/guardian/mixins.py", line 213, in dispatch
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 194, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 382, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 409, in _clean_form
    cleaned_data = self.clean()
  File "/home/daisy/daisy/core/forms/dataset.py", line 43, in clean
    if contract.project:
AttributeError: 'NoneType' object has no attribute 'project'

```

logged in as Admin, commit: 78b62961638f87bfe5b5a81b3409622cc25d5310

**Comment by pinarpink** [comment] 2019-07-30 08:34
hi @vildead ,
for the second error, I was not able to reproduce. I'll try to look at the data. Which dataset is this on the test server?
cheers

**Comment by vildead** [comment] 2019-07-31 14:43
@pinarpink I can't reproduce this error on commit c4014c78bf9ee50c15a23297169d9d985da38d24
if you have no updates on my first point, we can close the issue since the second point was probably solved by update of permissions.

**Comment by pinarpink** [comment] 2019-07-31 14:52
@vildead  let's keep this open. I'll see if the validation messages can be more informative on existing connections

**Comment by vildead** [comment] 2019-08-02 10:33
closing the issue. Verified on commit: 425fc268cf69a491767617d0b4bfe5562158c988

**Closed by vildead** 2019-08-02 10:33 UTC
Labels: to-be-verified
